//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XAssert.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultAssertProviderMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultAssertProviderMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XAssert.Resources.DefaultAssertProviderMessages", typeof(DefaultAssertProviderMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.AreEqual(first = &apos;{0}&apos;, second = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string AreEqual {
            get {
                return ResourceManager.GetString("AreEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.AreNotEqual(first = &apos;{0}&apos;, second = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string AreNotEqual {
            get {
                return ResourceManager.GetString("AreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.AreNotSame(first = &apos;{0}&apos;, second = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string AreNotSame {
            get {
                return ResourceManager.GetString("AreNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.AreSame(first = &apos;{0}&apos;, second = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string AreSame {
            get {
                return ResourceManager.GetString("AreSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.DoesNotEndWith(str = &apos;{0}&apos;, part = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string DoesNotEndWith {
            get {
                return ResourceManager.GetString("DoesNotEndWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.DoesNotMatch(str = &apos;{0}&apos;, regex = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string DoesNotMatch {
            get {
                return ResourceManager.GetString("DoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.DoesNotStartWith(str = &apos;{0}&apos;, part = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string DoesNotStartWith {
            get {
                return ResourceManager.GetString("DoesNotStartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.DoesNotThrow&lt;TException = &apos;{0}&apos;&gt;(action = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string DoesNotThrow {
            get {
                return ResourceManager.GetString("DoesNotThrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.EndsWith(str = &apos;{0}&apos;, part = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string EndsWith {
            get {
                return ResourceManager.GetString("EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.Contains(enumerable&apos; {0}&apos;, item = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string EnumerableContains {
            get {
                return ResourceManager.GetString("EnumerableContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.DoesNotContain(enumerable &apos;{0}&apos;, item = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string EnumerableDoesNotContain {
            get {
                return ResourceManager.GetString("EnumerableDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsDefault(enumerable = &apos;{0}&apos;) failure.
        /// </summary>
        internal static string EnumerableIsEmpty {
            get {
                return ResourceManager.GetString("EnumerableIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.EnumerableIsNotEmpty(enumerable = &apos;{0}&apos;) failure.
        /// </summary>
        internal static string EnumerableIsNotEmpty {
            get {
                return ResourceManager.GetString("EnumerableIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsEmpty(value = &apos;{0}&apos;) failure.
        /// </summary>
        internal static string GuidIsEmpty {
            get {
                return ResourceManager.GetString("GuidIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsNotEmpty(value = &apos;{0}&apos;) failure.
        /// </summary>
        internal static string GuidIsNotEmpty {
            get {
                return ResourceManager.GetString("GuidIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsDefault(obj = &apos;{0}&apos;) failure.
        /// </summary>
        internal static string IsDefault {
            get {
                return ResourceManager.GetString("IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsFalse(value = &apos;{0}&apos;) failure.
        /// </summary>
        internal static string IsFalse {
            get {
                return ResourceManager.GetString("IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsGreaterThan(first = &apos;{0}&apos;, second = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string IsGreaterThan {
            get {
                return ResourceManager.GetString("IsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsGreaterThanOrEqual(first = &apos;{0}&apos;, second = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string IsGreaterThanOrEqual {
            get {
                return ResourceManager.GetString("IsGreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsLessThan(first = &apos;{0}&apos;, second = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string IsLessThan {
            get {
                return ResourceManager.GetString("IsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsLessThanOrEqual(first = &apos;{0}&apos;, second = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string IsLessThanOrEqual {
            get {
                return ResourceManager.GetString("IsLessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsNaN(value = &apos;{0}&apos;) failure.
        /// </summary>
        internal static string IsNaN {
            get {
                return ResourceManager.GetString("IsNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsNegativeInfinity(value = &apos;{0}&apos;) failure.
        /// </summary>
        internal static string IsNegativeInfinity {
            get {
                return ResourceManager.GetString("IsNegativeInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsNotDefault(obj = &apos;{0}&apos;) failure.
        /// </summary>
        internal static string IsNotDefault {
            get {
                return ResourceManager.GetString("IsNotDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsNotNaN(value = &apos;{0}&apos;) failure.
        /// </summary>
        internal static string IsNotNaN {
            get {
                return ResourceManager.GetString("IsNotNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsNotNegativeInfinity(value = &apos;{0}&apos;) failure.
        /// </summary>
        internal static string IsNotNegativeInfinity {
            get {
                return ResourceManager.GetString("IsNotNegativeInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsNotOfType(type = &apos;{0}&apos;, obj = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string IsNotOfType {
            get {
                return ResourceManager.GetString("IsNotOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsNotOfTypeAssignableFrom(type = &apos;{0}&apos;, obj = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string IsNotOfTypeAssignableFrom {
            get {
                return ResourceManager.GetString("IsNotOfTypeAssignableFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsNotOfTypeAssignableTo(type = &apos;{0}&apos;, obj = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string IsNotOfTypeAssignableTo {
            get {
                return ResourceManager.GetString("IsNotOfTypeAssignableTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsNotPositiveInfinity(value = &apos;{0}&apos;) failure.
        /// </summary>
        internal static string IsNotPositiveInfinity {
            get {
                return ResourceManager.GetString("IsNotPositiveInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsOfType(type = &apos;{0}&apos;, obj = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string IsOfType {
            get {
                return ResourceManager.GetString("IsOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsOfTypeAssignableFrom(type = &apos;{0}&apos;, obj = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string IsOfTypeAssignableFrom {
            get {
                return ResourceManager.GetString("IsOfTypeAssignableFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsOfTypeAssignableTo(type = &apos;{0}&apos;, obj = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string IsOfTypeAssignableTo {
            get {
                return ResourceManager.GetString("IsOfTypeAssignableTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsPositiveInfinity(value = &apos;{0}&apos;) failure.
        /// </summary>
        internal static string IsPositiveInfinity {
            get {
                return ResourceManager.GetString("IsPositiveInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsTrue(value = &apos;{0}&apos;) failure.
        /// </summary>
        internal static string IsTrue {
            get {
                return ResourceManager.GetString("IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.Matches(str = &apos;{0}&apos;, regex = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsNotNull(obj = &apos;{0}&apos;) failure.
        /// </summary>
        internal static string ObjectIsNotNull {
            get {
                return ResourceManager.GetString("ObjectIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsNull(obj = &apos;{0}&apos;) failure.
        /// </summary>
        internal static string ObjectIsNull {
            get {
                return ResourceManager.GetString("ObjectIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.StartsWith(str = &apos;{0}&apos;, part = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string StartsWith {
            get {
                return ResourceManager.GetString("StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.Contains(str = &apos;{0}&apos;, part = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string StringContains {
            get {
                return ResourceManager.GetString("StringContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.DoesNotContain(str = &apos;{0}&apos;, part = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string StringDoesNotContain {
            get {
                return ResourceManager.GetString("StringDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.Throws&lt;TException = &apos;{0}&apos;&gt;(action = &apos;{1}&apos;) failure.
        /// </summary>
        internal static string Throws {
            get {
                return ResourceManager.GetString("Throws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsNotNull(value = &apos;{0}&apos;) failure.
        /// </summary>
        internal static string ValueIsNotNull {
            get {
                return ResourceManager.GetString("ValueIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultAssertProvider.IsNull(value = &apos;{0}&apos;) failure.
        /// </summary>
        internal static string ValueIsNull {
            get {
                return ResourceManager.GetString("ValueIsNull", resourceCulture);
            }
        }
    }
}
